package mocks

import "github.com/test-go/testify/mock"

// CoinGeckoAPI is an autogenerated mock type for the CoinGeckoAPI type
type CoinGeckoAPI struct {
	mock.Mock
}

// GetPrice provides a mock function with given fields: symbol, date
func (_m *CoinGeckoAPI) GetPrice(symbol string, date string) (float64, error) {
	ret := _m.Called(symbol, date)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string, string) float64); ok {
		r0 = rf(symbol, date)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(symbol, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenID provides a mock function with given fields: token
func (_m *CoinGeckoAPI) GetTokenID(token string) string {
	ret := _m.Called(token)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InitTokenIDs provides a mock function with given fields:
func (_m *CoinGeckoAPI) InitTokenIDs() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
