package mocks

import (
	internal "github.com/lat1992/blockchain-data-aggregator/internal"
	"github.com/test-go/testify/mock"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// InsertMarket provides a mock function with given fields: stats
func (_m *Database) InsertMarket(stats map[string]internal.MarketStat) error {
	ret := _m.Called(stats)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]internal.MarketStat) error); ok {
		r0 = rf(stats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
